name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout to repo
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: "Hola mudno"
        run: echo 'hola mundo'
      - name: "Date"
        run: date
      - name: "Dir"
        run: ls -la
