name: CI/CD NodeJS

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.0

      - name: Import NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run install
        run: npm install

      - name: Show content
        run: ls -l

